version: '3'
services:
  backend:
    container_name: myDictionary-monolithic-be
    image: ceqo/dictionary-monolithic-be:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dictionary
      - SPRING_DATASOURCE_USERNAME=dictionary
      - SPRING_DATASOURCE_PASSWORD=dictionarypass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - server.port=8080
      - spring.application.name=myDictionary


  angularapp:
    container_name: myDictionary-monolithic-fe-l
    image: ceqo/dictionary-monolithic-fe-l:latest
    ports:
      - "4200:80/tcp"

  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dictionary
      - POSTGRES_PASSWORD=dictionarypass
